import {
  CrmCustomer,
  CrmContact,
  CrmDealOpportunity,
  CrmActivity,
  CrmTask,
  CrmSupplierPartner,
  CrmAiInsight
} from '../types.js';

const now = new Date().toISOString();
const yesterday = new Date(Date.now() - 86400000).toISOString();
const twoDaysAgo = new Date(Date.now() - 172800000).toISOString();
const threeDaysAgo = new Date(Date.now() - 259200000).toISOString();
const tomorrow = new Date(Date.now() + 86400000).toISOString();
const inTwoDays = new Date(Date.now() + 172800000).toISOString();

export const DEFAULT_CRM_CUSTOMERS: CrmCustomer[] = [
  {
    id: 'cust-don-pepe',
    tenantId: 'tenant-cdmx-01',
    name: 'Abarrotes Don Pepe',
    businessName: 'Comercializadora Don Pepe S.A. de C.V.',
    type: 'TIENDA_ABARROTES',
    status: 'ACTIVO',
    segment: 'TIER_A',
    phone: '55 4123 9081',
    email: 'contacto@abarrotesdonpepe.com',
    address: 'República de Uruguay 42, Centro Histórico',
    city: 'Ciudad de México',
    zone: 'CENTRO',
    assignedTo: 'Carlos Mendoza (Operaciones)',
    createdAt: '2026-01-15T08:00:00.000Z',
    updatedAt: now,
    lastActivityAt: now,
    monthlySales: 84500,
    avgTicket: 115.5,
    purchaseFrequencyDays: 3,
    monitoredSkus: 248,
    grossMarginPercent: 26.4,
    churnRiskScore: 12,
    lastPurchaseDate: yesterday,
    daysSinceLastPurchase: 1,
    estimatedLTV: 1014000,
    notes: 'Tienda ancla en zona Centro con alto flujo de paso. Excelente historial de pago y adopción del Store Brain.',
    tags: ['ALTA_ROTACION', 'STORE_BRAIN_VIP', 'CDMX_CENTRO']
  },
  {
    id: 'cust-lupita',
    tenantId: 'tenant-cdmx-02',
    name: 'Super Abarrotes La Lupita',
    businessName: 'Minisuper y Abarrotes La Lupita S. de R.L.',
    type: 'MINISUPER',
    status: 'ACTIVO',
    segment: 'TIER_A',
    phone: '55 8834 1122',
    email: 'lupita@superlalupita.mx',
    address: 'Calzada Ermita Iztapalapa 1820, Los Ángeles',
    city: 'Ciudad de México',
    zone: 'IZTAPALAPA',
    assignedTo: 'Sofia Valdés (Customer Success)',
    createdAt: '2026-02-01T09:30:00.000Z',
    updatedAt: now,
    lastActivityAt: yesterday,
    monthlySales: 135000,
    avgTicket: 182.0,
    purchaseFrequencyDays: 2,
    monitoredSkus: 420,
    grossMarginPercent: 24.8,
    churnRiskScore: 18,
    lastPurchaseDate: yesterday,
    daysSinceLastPurchase: 1,
    estimatedLTV: 1620000,
    notes: 'Minisuper con área de cremería y abarrotes. Compra volumen mayorista directo en Scorpion Iztapalapa.',
    tags: ['MINISUPER', 'IZTAPALAPA', 'VOLUMEN_MAYORISTA']
  },
  {
    id: 'cust-dos-carnales',
    tenantId: 'tenant-cdmx-03',
    name: 'Abarrotes Los Dos Carnales',
    businessName: 'Hermanos Hernández Abarroteros',
    type: 'TIENDA_ABARROTES',
    status: 'EN_RIESGO',
    segment: 'TIER_B',
    phone: '55 3390 4411',
    email: 'roberto@dos-carnales.com',
    address: 'Av. Gran Canal 512, San Juan de Aragón',
    city: 'Ciudad de México',
    zone: 'GUSTAVO_A_MADERO',
    assignedTo: 'Carlos Mendoza (Operaciones)',
    createdAt: '2026-03-10T11:00:00.000Z',
    updatedAt: now,
    lastActivityAt: threeDaysAgo,
    monthlySales: 48200,
    avgTicket: 78.0,
    purchaseFrequencyDays: 6,
    monitoredSkus: 160,
    grossMarginPercent: 19.5,
    churnRiskScore: 68,
    lastPurchaseDate: threeDaysAgo,
    daysSinceLastPurchase: 6,
    estimatedLTV: 578400,
    notes: 'Alerta: Caída de margen al 19.5% por incremento de precios de proveedores no trasladados al público. Requiere asesoría urgente.',
    tags: ['RIESGO_CHURN', 'MARGEN_BAJO', 'GAM']
  },
  {
    id: 'cust-central-snack',
    tenantId: 'tenant-cdmx-04',
    name: 'Miscelánea El Rinconcito',
    businessName: 'Patricia Morales Cruz',
    type: 'TIENDA_ABARROTES',
    status: 'ACTIVO',
    segment: 'TIER_B',
    phone: '55 6712 3344',
    email: 'patricia.morales@elrinconcito.mx',
    address: 'Calle Laguna de Mayrán 120, Anáhuac',
    city: 'Ciudad de México',
    zone: 'MIGUEL_HIDALGO',
    assignedTo: 'Sofia Valdés (Customer Success)',
    createdAt: '2026-04-05T14:00:00.000Z',
    updatedAt: now,
    lastActivityAt: twoDaysAgo,
    monthlySales: 62400,
    avgTicket: 95.0,
    purchaseFrequencyDays: 4,
    monitoredSkus: 195,
    grossMarginPercent: 25.2,
    churnRiskScore: 22,
    lastPurchaseDate: twoDaysAgo,
    daysSinceLastPurchase: 2,
    estimatedLTV: 748800,
    notes: 'Negocio familiar con clientela fiel de oficinas y vecinos. Buena rotación en botanas, refrescos y lácteos.',
    tags: ['ANAHUAC', 'SNACKS_BEBIDAS', 'ACTIVO']
  },
  {
    id: 'cust-bodega-cuauhtemoc',
    tenantId: 'tenant-cdmx-05',
    name: 'Minisuper Express Cuauhtémoc',
    businessName: 'Operadora de Minisupers del Valle S.A.',
    type: 'MINISUPER',
    status: 'ACTIVO',
    segment: 'ENTERPRISE',
    phone: '55 5511 9988',
    email: 'cnavarrete@minisuper-express.com',
    address: 'Av. Cuauhtémoc 320, Roma Sur',
    city: 'Ciudad de México',
    zone: 'CUAUHTEMOC',
    assignedTo: 'Carlos Mendoza (Operaciones)',
    createdAt: '2026-01-20T10:00:00.000Z',
    updatedAt: now,
    lastActivityAt: now,
    monthlySales: 210000,
    avgTicket: 245.0,
    purchaseFrequencyDays: 1,
    monitoredSkus: 680,
    grossMarginPercent: 28.1,
    churnRiskScore: 8,
    lastPurchaseDate: now,
    daysSinceLastPurchase: 0,
    estimatedLTV: 2520000,
    notes: 'Cuenta Enterprise multi-caja. Utiliza sincronización automática de catálogo con Zorro y Scorpion.',
    tags: ['ENTERPRISE', 'ROMA_SUR', 'MULTI_CAJA', 'STORE_BRAIN_PRO']
  },
  {
    id: 'cust-fruteria-providencia',
    tenantId: 'tenant-cdmx-06',
    name: 'Abarrotes & Cremería La Providencia',
    businessName: 'Elena Ramos y Cía.',
    type: 'TIENDA_ABARROTES',
    status: 'PROSPECTO',
    segment: 'TIER_C',
    phone: '55 7722 0099',
    email: 'providencia.abastos@gmail.com',
    address: 'Pasillo 4 Letra K, Central de Abastos',
    city: 'Ciudad de México',
    zone: 'CENTRAL_ABASTOS',
    assignedTo: 'Sofia Valdés (Customer Success)',
    createdAt: '2026-08-01T12:00:00.000Z',
    updatedAt: now,
    lastActivityAt: yesterday,
    monthlySales: 35000,
    avgTicket: 65.0,
    purchaseFrequencyDays: 7,
    monitoredSkus: 110,
    grossMarginPercent: 21.0,
    churnRiskScore: 45,
    lastPurchaseDate: twoDaysAgo,
    daysSinceLastPurchase: 3,
    estimatedLTV: 420000,
    notes: 'En proceso de integración de catálogo. Interesados en comparador de precios de abarrotes de la Central.',
    tags: ['PROSPECTO', 'CENTRAL_ABASTOS', 'ONBOARDING']
  }
];

export const DEFAULT_CRM_CONTACTS: CrmContact[] = [
  {
    id: 'cnt-01',
    customerId: 'cust-don-pepe',
    tenantId: 'tenant-cdmx-01',
    name: 'José Luis Gómez (Don Pepe)',
    role: 'PROPIETARIO',
    phone: '55 4123 9081',
    email: 'jose.pepe@abarrotesdonpepe.com',
    isPrimary: true,
    status: 'ACTIVO',
    preferences: 'Prefiere contacto por WhatsApp en las mañanas (08:00 - 11:00)',
    lastInteractionAt: now,
    assignedTo: 'Carlos Mendoza',
    notes: 'Toma las decisiones finales de compra y precios de venta al público.',
    createdAt: '2026-01-15T08:30:00.000Z'
  },
  {
    id: 'cnt-02',
    customerId: 'cust-don-pepe',
    tenantId: 'tenant-cdmx-01',
    name: 'Mario Gómez',
    role: 'ENCARGADO_COMPRAS',
    phone: '55 4123 9082',
    email: 'mario.compras@abarrotesdonpepe.com',
    isPrimary: false,
    status: 'ACTIVO',
    preferences: 'Revisa cotizaciones vía email los lunes y jueves',
    lastInteractionAt: yesterday,
    assignedTo: 'Carlos Mendoza',
    notes: 'Hijo de Don Pepe, coordina descargas de pedidos y verificación de facturas.',
    createdAt: '2026-01-15T08:30:00.000Z'
  },
  {
    id: 'cnt-03',
    customerId: 'cust-lupita',
    tenantId: 'tenant-cdmx-02',
    name: 'Guadalupe Martínez',
    role: 'PROPIETARIO',
    phone: '55 8834 1122',
    email: 'lupita@superlalupita.mx',
    isPrimary: true,
    status: 'ACTIVO',
    preferences: 'WhatsApp directo o visita presencial',
    lastInteractionAt: yesterday,
    assignedTo: 'Sofia Valdés',
    notes: 'Negocia descuentos por volumen en abarrotes secos y productos de limpieza.',
    createdAt: '2026-02-01T10:00:00.000Z'
  },
  {
    id: 'cnt-04',
    customerId: 'cust-dos-carnales',
    tenantId: 'tenant-cdmx-03',
    name: 'Roberto Hernández',
    role: 'PROPIETARIO',
    phone: '55 3390 4411',
    email: 'roberto@dos-carnales.com',
    isPrimary: true,
    status: 'ACTIVO',
    preferences: 'Llamada telefónica a partir de las 16:00 hrs',
    lastInteractionAt: threeDaysAgo,
    assignedTo: 'Carlos Mendoza',
    notes: 'Preocupado por la competencia cercana de tiendas 3B y OXXO.',
    createdAt: '2026-03-10T11:30:00.000Z'
  },
  {
    id: 'cnt-05',
    customerId: 'cust-bodega-cuauhtemoc',
    tenantId: 'tenant-cdmx-05',
    name: 'Carlos Navarrete',
    role: 'ADMINISTRADOR',
    phone: '55 5511 9988',
    email: 'cnavarrete@minisuper-express.com',
    isPrimary: true,
    status: 'ACTIVO',
    preferences: 'Canal de Slack / WhatsApp Business y reportes en Excel',
    lastInteractionAt: now,
    assignedTo: 'Carlos Mendoza',
    notes: 'Administra compras y márgenes de 3 tiendas en la alcaldía Cuauhtémoc.',
    createdAt: '2026-01-20T10:30:00.000Z'
  }
];

export const DEFAULT_CRM_OPPORTUNITIES: CrmDealOpportunity[] = [
  {
    id: 'crm-opp-01',
    customerId: 'cust-don-pepe',
    tenantId: 'tenant-cdmx-01',
    customerName: 'Abarrotes Don Pepe',
    title: 'Abastecimiento Mayoreo Aceite 123 en Scorpion',
    stage: 'PROPUESTA',
    value: 4500,
    estimatedSavings: 680,
    probability: 85,
    expectedCloseDate: tomorrow,
    source: 'AI_INVENTORY_AGENT',
    assignedTo: 'Carlos Mendoza',
    notes: 'Scorpion tiene caja de 12 botellas a $37.50 vs $43.20 de distribuidor local.',
    nextAction: 'Confirmar orden y generar orden de compra',
    nextActionDate: tomorrow,
    createdAt: yesterday,
    updatedAt: now
  },
  {
    id: 'crm-opp-02',
    customerId: 'cust-lupita',
    tenantId: 'tenant-cdmx-02',
    customerName: 'Super Abarrotes La Lupita',
    title: 'Optimización Canasta Limpieza (Cloralex + Fabuloso)',
    stage: 'NEGOCIACION',
    value: 12800,
    estimatedSavings: 1920,
    probability: 90,
    expectedCloseDate: inTwoDays,
    source: 'AI_PRICE_MONITOR',
    assignedTo: 'Sofia Valdés',
    notes: 'Zorro Abarrotero activó promoción 3x2 en bultos de detergente y blanqueador.',
    nextAction: 'Enviar comparativa de margen por WhatsApp a Doña Lupita',
    nextActionDate: tomorrow,
    createdAt: twoDaysAgo,
    updatedAt: now
  },
  {
    id: 'crm-opp-03',
    customerId: 'cust-dos-carnales',
    tenantId: 'tenant-cdmx-03',
    customerName: 'Abarrotes Los Dos Carnales',
    title: 'Plan de Rescate de Margen en Granos y Harinas',
    stage: 'CONTACTADO',
    value: 3200,
    estimatedSavings: 490,
    probability: 65,
    expectedCloseDate: inTwoDays,
    source: 'STORE_BRAIN',
    assignedTo: 'Carlos Mendoza',
    notes: 'Sustituir proveedor intermediario por compra directa en Central de Abastos o Mayoreo Total.',
    nextAction: 'Llamada de asesoría con Don Roberto para ajustar precios de venta',
    nextActionDate: tomorrow,
    createdAt: threeDaysAgo,
    updatedAt: now
  },
  {
    id: 'crm-opp-04',
    customerId: 'cust-bodega-cuauhtemoc',
    tenantId: 'tenant-cdmx-05',
    customerName: 'Minisuper Express Cuauhtémoc',
    title: 'Suministro Consolidado Semanal Zorro + Scorpion',
    stage: 'GANADO',
    value: 28500,
    estimatedSavings: 4200,
    probability: 100,
    expectedCloseDate: now,
    source: 'REORDER_SIGNAL',
    assignedTo: 'Carlos Mendoza',
    notes: 'Cierre de pedido consolidado de 45 SKUs con ahorro certificado del 14.7%.',
    nextAction: 'Supervisar entrega de CEDIS programada para el jueves',
    nextActionDate: inTwoDays,
    createdAt: '2026-08-10T10:00:00.000Z',
    updatedAt: now
  }
];

export const DEFAULT_CRM_ACTIVITIES: CrmActivity[] = [
  {
    id: 'act-01',
    customerId: 'cust-don-pepe',
    tenantId: 'tenant-cdmx-01',
    opportunityId: 'crm-opp-01',
    type: 'WHATSAPP',
    title: 'Envío de cotización con descuento Scorpion',
    description: 'Se envió desglose de ahorro ($680 MXN) en Aceite 123 y Arroz SOS a Don Pepe.',
    performedBy: 'Carlos Mendoza',
    outcome: 'Don Pepe confirmó interés; revisará con su hijo Mario por la tarde.',
    completedAt: now,
    createdAt: now
  },
  {
    id: 'act-02',
    customerId: 'cust-lupita',
    tenantId: 'tenant-cdmx-02',
    opportunityId: 'crm-opp-02',
    type: 'LLAMADA',
    title: 'Llamada de confirmación de pedido mayorista',
    description: 'Revisión telefónica con Doña Lupita sobre volumen de jabón y detergente.',
    performedBy: 'Sofia Valdés',
    outcome: 'Acordado pedido de 15 cajas; solicitud de entrega el viernes.',
    completedAt: yesterday,
    createdAt: yesterday
  },
  {
    id: 'act-03',
    customerId: 'cust-dos-carnales',
    tenantId: 'tenant-cdmx-03',
    type: 'VISITA',
    title: 'Visita presencial y auditoría de góndola',
    description: 'Revisión en sitio de rotación y etiquetado de precios en San Juan de Aragón.',
    performedBy: 'Carlos Mendoza',
    outcome: 'Se detectó que no habían actualizado precios en 3 semanas. Se programó ajuste.',
    completedAt: twoDaysAgo,
    createdAt: twoDaysAgo
  },
  {
    id: 'act-04',
    customerId: 'cust-bodega-cuauhtemoc',
    tenantId: 'tenant-cdmx-05',
    opportunityId: 'crm-opp-04',
    type: 'AI_EVENT',
    title: 'Store Brain ejecutó optimización autónoma de precios',
    description: 'El motor analítico sincronizó 18 SKUs con márgenes optimizados (+3.2%).',
    performedBy: 'StoreBrain / AI Agent',
    outcome: 'Aprobación automática bajo umbral de gobernanza ($15,000 MXN).',
    completedAt: now,
    createdAt: now
  }
];

export const DEFAULT_CRM_TASKS: CrmTask[] = [
  {
    id: 'task-01',
    customerId: 'cust-don-pepe',
    tenantId: 'tenant-cdmx-01',
    customerName: 'Abarrotes Don Pepe',
    opportunityId: 'crm-opp-01',
    title: 'Confirmar autorización de orden Scorpion con Don Pepe',
    description: 'Verificar si Mario ya validó el espacio en bodega para recibir 10 cajas de aceite.',
    assignedTo: 'Carlos Mendoza',
    priority: 'ALTA',
    status: 'HOY',
    dueDate: now,
    source: 'AI_AUTONOMOUS',
    createdAt: yesterday
  },
  {
    id: 'task-02',
    customerId: 'cust-dos-carnales',
    tenantId: 'tenant-cdmx-03',
    customerName: 'Abarrotes Los Dos Carnales',
    title: 'Llamada de alerta de margen crítico con Roberto Hernández',
    description: 'Explicar por qué están perdiendo 6% de margen en harinas y presentar lista de precios mayoristas.',
    assignedTo: 'Carlos Mendoza',
    priority: 'CRITICA',
    status: 'HOY',
    dueDate: now,
    source: 'AI_AUTONOMOUS',
    createdAt: yesterday
  },
  {
    id: 'task-03',
    customerId: 'cust-lupita',
    tenantId: 'tenant-cdmx-02',
    customerName: 'Super Abarrotes La Lupita',
    opportunityId: 'crm-opp-02',
    title: 'Enviar comparativa de precios Zorro vs Scorpion en Limpieza',
    description: 'Generar PDF ejecutivo con comparativa de 12 SKUs clave de limpieza.',
    assignedTo: 'Sofia Valdés',
    priority: 'MEDIA',
    status: 'PENDIENTE',
    dueDate: tomorrow,
    source: 'MANUAL_OPERATOR',
    createdAt: yesterday
  },
  {
    id: 'task-04',
    customerId: 'cust-bodega-cuauhtemoc',
    tenantId: 'tenant-cdmx-05',
    customerName: 'Minisuper Express Cuauhtémoc',
    title: 'Auditar entrega de CEDIS Scorpion en sucursal Roma Sur',
    description: 'Confirmar que las facturas y lotes recibidos coincidan con la orden del Store Brain.',
    assignedTo: 'Carlos Mendoza',
    priority: 'MEDIA',
    status: 'COMPLETADA',
    dueDate: yesterday,
    source: 'MANUAL_OPERATOR',
    completedAt: yesterday,
    createdAt: threeDaysAgo
  }
];

export const DEFAULT_CRM_SUPPLIERS: CrmSupplierPartner[] = [
  {
    id: 'supp-zorro',
    name: 'Zorro Abarrotero',
    contactPerson: 'Lic. Fernando Garza (Cuentas Clave)',
    phone: '55 5784 9020',
    email: 'institucional@zorroabarrotero.com.mx',
    categories: ['Abarrotes Comestibles', 'Lácteos', 'Limpieza', 'Vinos y Licores'],
    coverage: 'CDMX, EdoMex, Hidalgo, Morelos',
    commercialTerms: 'Contado comercial, crédito 7 días a partir de $50k/mes',
    leadTimeDays: 1,
    minOrderAmount: 1500,
    creditDays: 7,
    reliabilityScore: 98,
    lastQuoteAt: now,
    score: 9.8,
    activePromosCount: 14
  },
  {
    id: 'supp-scorpion',
    name: 'Comercializadora Scorpion',
    contactPerson: 'Ing. Mauricio Tapia (Ventas Mayoristas)',
    phone: '55 5634 1100',
    email: 'mayoreo@scorpion.com.mx',
    categories: ['Abarrotes Secos', 'Aceites y Granos', 'Higiene Personal', 'Dulcería'],
    coverage: 'CDMX Metropolitana, Puebla, Querétaro',
    commercialTerms: 'Precios de escala por caja/pallet, recolección en CEDIS o envío gratis >$3,500',
    leadTimeDays: 1,
    minOrderAmount: 2000,
    creditDays: 15,
    reliabilityScore: 96,
    lastQuoteAt: now,
    score: 9.6,
    activePromosCount: 19
  },
  {
    id: 'supp-mayoreo-total',
    name: 'Mayoreo Total México',
    contactPerson: 'Lic. Claudia Beltrán',
    phone: '55 1209 8877',
    email: 'ventas@mayoreototal.mx',
    categories: ['Enlatados', 'Harinas', 'Café y Té', 'Bebidas'],
    coverage: 'Nacional y CDMX Centro',
    commercialTerms: 'Pago en línea con factura electrónica inmediata',
    leadTimeDays: 2,
    minOrderAmount: 1000,
    creditDays: 0,
    reliabilityScore: 92,
    lastQuoteAt: yesterday,
    score: 9.2,
    activePromosCount: 8
  },
  {
    id: 'supp-surtitienda',
    name: 'Surtitienda Central de Abastos',
    contactPerson: 'Don Rogelio Esquivel',
    phone: '55 5694 4000',
    email: 'pedidos@surtitienda.com.mx',
    categories: ['Semillas', 'Chiles Secos', 'Especias', 'Granos a Granel'],
    coverage: 'Central de Abastos Iztapalapa & CDMX Oriente',
    commercialTerms: 'Pago contra entrega en efectivo o transferencia SPEI',
    leadTimeDays: 1,
    minOrderAmount: 800,
    creditDays: 0,
    reliabilityScore: 94,
    lastQuoteAt: yesterday,
    score: 9.4,
    activePromosCount: 11
  }
];

export const DEFAULT_CRM_AI_INSIGHTS: CrmAiInsight[] = [
  {
    id: 'insight-01',
    customerId: 'cust-dos-carnales',
    tenantId: 'tenant-cdmx-03',
    customerName: 'Abarrotes Los Dos Carnales',
    type: 'CHURN_RISK',
    severity: 'CRITICO',
    title: 'Riesgo Crítico de Churn: Margen en 19.5% y 6 días sin resurtir',
    description: 'La tienda está absorbiendo incrementos de costo de harinas y granos sin ajustar el PVP, lo que mermó su flujo de caja.',
    estimatedImpact: 4800,
    suggestedAction: 'Programar llamada de reactivación y enviar canasta de resurtido con 28% de margen garantizado en Scorpion.',
    confidence: 0.94,
    generatedAt: now,
    dismissed: false
  },
  {
    id: 'insight-02',
    customerId: 'cust-don-pepe',
    tenantId: 'tenant-cdmx-01',
    customerName: 'Abarrotes Don Pepe',
    type: 'SUPPLIER_SWITCH',
    severity: 'OPORTUNIDAD',
    title: 'Oportunidad de Switch: Ahorro de $680 MXN en Aceite Comestible',
    description: 'Comercializadora Scorpion ofrece la caja de Aceite 123 1L a $37.50/pza vs $43.20 de su proveedor tradicional.',
    estimatedImpact: 680,
    suggestedAction: 'Generar orden de compra directa a Scorpion y activar margen sugerido del 28%.',
    confidence: 0.96,
    generatedAt: now,
    dismissed: false
  },
  {
    id: 'insight-03',
    customerId: 'cust-lupita',
    tenantId: 'tenant-cdmx-02',
    customerName: 'Super Abarrotes La Lupita',
    type: 'REORDER_ALERT',
    severity: 'ALERTA',
    title: 'Alerta de Quiebre de Stock en Detergente en Polvo Roma 1kg',
    description: 'A la tasa de venta actual (3.8 pzas/día), el inventario se agotará en menos de 36 horas.',
    estimatedImpact: 1250,
    suggestedAction: 'Disparar orden de resurtido de 25 pzas en Zorro Abarrotero Aeropuerto.',
    confidence: 0.92,
    generatedAt: yesterday,
    dismissed: false
  },
  {
    id: 'insight-04',
    customerId: 'cust-bodega-cuauhtemoc',
    tenantId: 'tenant-cdmx-05',
    customerName: 'Minisuper Express Cuauhtémoc',
    type: 'MARGIN_LEAKAGE',
    severity: 'OPORTUNIDAD',
    title: 'Fuga de Margen Detectada en Botanas y Galletas Gamesa',
    description: 'La zona Roma Sur tolera un PVP de $19.00 vs el actual de $16.50 sin afectar la velocidad de venta.',
    estimatedImpact: 2100,
    suggestedAction: 'Ajustar PVP sugerido en terminal punto de venta (+15.1% margen adicional).',
    confidence: 0.89,
    generatedAt: now,
    dismissed: false
  }
];
