name: Build and deploy Node.js app to Azure Web App - abbarrotes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B62EC58580B24F13B4186572673DED82 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8D1B71182F0D4952A639E054EC2FDB34 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AB990D60B5F64C48AE1F8ECCBB120589 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: abbarrotes
